Update package.json to fix Regular Expression Denial of Service in debug
mapbox/node-pre-gyp pull request #706
Opened 2023-12-08 15:49 UTC by martinez-hugo

2024-04-18 16:14 UTC, cclauss commented
Please insert the line `- npm run update-crosswalk` after line 26 of the file `appveyor.yml` so we can see if your tests pass.

2024-06-29 15:19 UTC, cclauss commented
Please rebase or close this pull request.

2024-06-29 18:31 UTC, benmccann requested changes

2024-06-29 18:31 UTC, benmccann commented on test/proxy-bcrypt.test.js
> +const { HttpsProxyAgent } = require('https-proxy-agent');
if this is being updated, wouldn't you also have to update `lib/install.js`?

2024-11-26 23:49 UTC, benmccann commented
closing in favor of https://github.com/mapbox/node-pre-gyp/pull/747

2024-11-26 23:49 UTC, closed without merging